name: craftdet

dependencies:
  - python=3.11
  - pytorch
  - torchvision 
  - opencv
  - numpy
  - onnxruntime
  - fastapi
  - pip:
    - mmcv==2.1.0 -f https://download.openmmlab.com/mmcv/dist/cu121/torch2.1/index.html
    - gradio 
    - vietocr 
    - pdf2image